storage: /verdaccio/storage

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org

packages:
  "@gedai/*":
    access: $all
    publish: $all
    unpublish: $all
  "@*/*":
    access: $all
    proxy: npmjs
  "**":
    access: $all
    proxy: npmjs

logs:
  - { type: stdout, format: pretty, level: http }
